#v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  api-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: api-mysql
    volumes:
      - api-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api

  # PHP 7.3 + nginx
  app:
    image: ambientum/php:latest-nginx
    container_name: api-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
